### ISSUE TITLE
Closed connection

### ISSUE THREAD

**Issue by twistedindustries** [AMoo-Miki/homebridge-tuya-lan#27] opened 2019-03-13 21:33 UTC
One of my switches keeps throwing a "Closed connection with [deviceName]" in the log.  It looks like that is thrown when the socket connection is closed by the host.  I've got basically the same device and it works fine.  I can get this device to work if I remove it from the system and re-set everything up but it will only work for a bit and then becomes unresponsive.  Interesting to note I will get the closed connection message even when it does work.  It would be super awesome if I could get this solved.  Let me know any other information that'd be useful for debugging.

Also, thank you so much for the time spent on this.  It is so far the most stable of the homebridge/tuya plugins I've tried.

**Comment by AMoo-Miki** [comment] 2019-03-14 01:32
The connection closing is harmless; in the majority of the cases, the plugin will reuse the existing half-open socket to connect back and if the error was too sever, it would attempt to establish a fresh connection. The entire process shouldn't even take a full second. I have put in some extra logging messages for identifying the root cause of the disconnection. Use `npm i -g AMoo-Miki/homebridge-tuya-lan` to get the latest code and look for `[TuyaAccessory] Socket had a problem and will reconnect` which would give the error code.

Does this switch feel laggier than the other one? Does it feel like it responds slower than the other?

PS, I am glad that you are enjoying the plugin.

**Comment by twistedindustries** [comment] 2019-03-14 02:24
Ok I've done that updated the code and I'll check the logs when it starts to do it again.  It doesn't seem to be laggy or respond any slower than the other one.

**Comment by twistedindustries** [comment] 2019-03-14 03:19
I get the error basically straight away but once it becomes unresponsive these are the errors I'm seeing:

`[TuyaAccessory] Socket had a problem and will reconnect to Kitchen Light (Error: ERR_CONNECTION_TIMED_OUT)
[TuyaAccessory] Closed connection with Kitchen Light
[TuyaAccessory] Socket had a problem and will reconnect to Kitchen Light (ETIMEDOUT)`

**Comment by AMoo-Miki** [comment] 2019-03-14 09:46
I will submit a change to how connection timeout is measured and handled. Give it a shot to see if that helps. Whether it helps or not, any log it produced with `Socket had a problem and will reconnect to` would be helpful; even more helpful would be having timestamps for them and knowing what the last one was before loosing the device. Use `npm i -g AMoo-Miki/homebridge-tuya-lan` to get the latest code.

**Comment by twistedindustries** [comment] 2019-03-14 22:24
`Mar 14 20:40:02 octopi homebridge[19842]: [TuyaAccessory] Socket had a problem and will reconnect to Kitchen Light (ECONNRESET)
Mar 14 20:40:02 octopi homebridge[19842]: [TuyaAccessory] Closed connection with Kitchen Light
Mar 14 20:40:02 octopi homebridge[19842]: [TuyaAccessory] Socket had a problem and will reconnect to Kitchen Light (ECONNRESET)
Mar 14 20:40:02 octopi homebridge[19842]: [TuyaAccessory] Closed connection with Kitchen Light
Mar 14 20:40:32 octopi homebridge[19842]: [TuyaAccessory] Socket had a problem and will reconnect to Kitchen Light (Error: ERR_CONNECTION_TIMED_OUT)
Mar 14 20:40:32 octopi homebridge[19842]: [TuyaAccessory] Closed connection with Kitchen Light
Mar 14 20:41:07 octopi homebridge[19842]: [TuyaAccessory] Socket had a problem and will reconnect to Kitchen Light (Error: ERR_CONNECTION_TIMED_OUT)`

The moment it stopped responding was between 20:40:02 and 20:40:32.  A couple other notes, in order to get this device to work again I must:
- Reset the device generating new key
- Remove homebridge from homekit
- Remove accessories and persist folders
- Readd homebridge to homekit

If I don't generate a new key for the device it shows up and I can turn it on and off on my phone but the device doesn't actually turn on or off.  The errors in the log stay the same.

**Comment by AMoo-Miki** [comment] 2019-03-14 22:53
So looks like someone told the device to invalidate the key. When it stops responding in the Home app, can you still use it on the Tuya app **without an internet connection** on the phone? Is the device hooked up to any other services like IFTTT or ...?

This must be frustrating. You mentioned you have another identical device which is not giving you trouble; is there ANY difference whatsoever between the two? Can you look at the log and see how long it stayed connected?

Maybe I should write a separate piece of code to connect to this and do nothing and only log stuff to see why it is acting up.

Additionally, when you generate a new `key`, simply change the config file and restart Homebridge; don't do any of the other steps. See if that is enough to get the device to work.

Also, when using HomeKit, don't open the Tuya app ever; that can cause keys to get invalidated on some devices.

**Comment by twistedindustries** [comment] 2019-03-14 23:11
> So looks like someone told the device to invalidate the key. When it stops responding in the Home app, can you still use it on the Tuya app without an internet connection on the phone? Is the device hooked up to any other services like IFTTT or ...?

I can't access any device without an internet connection.  The device I am having trouble with works fine through the app [Smart Life].  I also hadn't opened the app at all between the device working and not working.

> is there ANY difference whatsoever between the two? Can you look at the log and see how long it stayed connected?

Not that I can see.  I checked the firmware and they are both the same.  I am not using IFTTT but I do have an Alexa with the smart life skill.  It looks like startup was at 20:25:40 and the first ECONNRESET happened at 20:35:21 [10 minutes after startup] and the first ERR_CONNECTION_TIMED_OUT error happening at 20:40:32 [15 minutes after startup].

> Additionally, when you generate a new key, simply change the config file and restart Homebridge; don't do any of the other steps. See if that is enough to get the device to work.

Yes, that was enough to make it work again.

**Comment by AMoo-Miki** [comment] 2019-03-15 01:41
Alexa wouldn't interrupt the device because it only talks to the Tuya Cloud; she is safe. I will cook an app that would only talk to this device and we will mess with it. Gimme till this weekend and I will get back to you.

**Comment by twistedindustries** [comment] 2019-03-16 19:16
This is so odd because every time it stops connecting I reset it but sometimes it lasts only an hour or so.  Sometimes it will last 18-20 hours.  Trying to pinpoint the exact thing that’s causing it to fail.

**Comment by twistedindustries** [comment] 2019-03-19 16:52
Ok, so now the switch has worked a few days.  I'm not sure what would cause it to stabilize but I am starting to wonder if this is something on their end and not something to do with this plugin.  I'd still be happy to run that script when you have it ready.  Just wanted to give you an update since it is so random.

**Comment by AMoo-Miki** [comment] 2019-04-08 09:13
Cool. Is it still working or has it given you trouble since then? I have been busy with an "alien abduction" case for the last month but let me know if it is still acting up and I will make that script.

**Comment by twistedindustries** [comment] 2019-04-08 15:54
No worries.  I understand.  Well, its sort of funny, it stopped working probably about a day after my last response.  Usually I fix it right away but I've been ignoring it for the last 2-1/2 to 3 weeks, I go to check this morning and it is working again.  So odd.  I'm happy to test whenever to help things get a bit more stable.

**Comment by AMoo-Miki** [comment] 2019-04-18 09:51
I have a feeling that the problem is just a simple wireless issue; well, it's more of a wishful thinking.

I will close this for you to open it back up when things become annoying again; I will then create some code to deal with it.

**Closed by AMoo-Miki** 2019-04-18 09:51 UTC
