### ISSUE TITLE
[TuyaLan] Failed to discover -NAME- (-ID-) in time but will keep looking.

### ISSUE THREAD

**Issue by VojGin** [AMoo-Miki/homebridge-tuya-lan#54] opened 2019-06-03 09:17 UTC
Did everything just like the instructions say.
Received id and key pair and added it into config file.
When homebridge restarts, I'm getting:

```
[TuyaLan] Failed to discover Socket (10343760bcddc2232f7a) in time but will keep looking.
```

My config file:
```
{
  "platform": "TuyaLan",
  "devices": [
    {
      "name": "Deer Light",
      "type": "Outlet",
      "manufacturer": "BlitzWolf",
      "model": "BW-SHP6",
      "id": "10343760bcddc2232f7a",
      "key": "-KEY-"
    }
  ]
}
```

Any idea what could be wrong?

**Comment by scsammyk** [comment] 2019-06-05 13:52
The same thing is happening with my setup. Any guidance would be appreciated. 

The device I am trying to connect to is a door/window sensor and I set it up as a SimpleLight as asked for unknown devices. It is possible my problem has something to do with the fact that it is a sensor and not a device like a switch or outlet.

**Comment by TheHomekitWayFinder** [comment] 2019-06-05 23:21
It is very possible that I could be to do with the device type that you are telling homebridge which is causing it to look for different codes along with the if and key so what I recommend doing is opening another issue and put it as a device support request and then reference this issue. I don’t know how long it will take as no one has been able to get in contact with AMoo-Miki via GitHub recently.

**Comment by iaansari** [comment] 2019-06-11 15:26
I was having the exact same issue with the same error messages for my Smart Plugs (Type Outlet). However they resolved on their own once I upgraded the firmware on my plugs. So I suspect this is more of an API / firmeware issue on the TuyaLan side than a homebrige plugin problem. Perhaps TuyaLan is limiting API access to only the latest firmware release?

**Comment by scsammyk** [comment] 2019-06-14 01:25
What version of the firmware are your devices on? Mine says it is on the latest

**Comment by fergburg** [comment] 2019-06-14 01:28
I have the error on 1.0.3 which it says is the latest firmware. The one which is on an earlier version still works.

**Comment by scsammyk** [comment] 2019-06-14 01:31
Is that the MCU version or the Wi-if version? Mine are 1.0.0 and 1.0.6 respectively

**Comment by fergburg** [comment] 2019-06-14 01:35
On the Outlet which has this error, both the MCU Module and Wifi Module are on 1.0.3, which it says is the latest version. 

This is the outlet I'm using: https://www.bunnings.com.au/brilliant-smart-wifi-plug-and-usb-charger_p0091644

**Comment by iaansari** [comment] 2019-06-14 15:13
My MCU and WIFI Modules are both at 1.0.1 which I am being told is the latest version. I use the following plugs https://www.amazon.ca/TECKIN-Wireless-Compatible-Function-Required/dp/B07PZ7VVGC/ref=sr_1_2_sspa?keywords=smart+plug&qid=1560525067&s=gateway&sr=8-2-spons&psc=1

So perhaps this is an issue with newer version of the firmware. Ideally what we need is the ability to specify the devices via IP vs having the homebrige plugin try to automatically discover them.

**Comment by palla89** [comment] 2019-06-17 22:48
Same problem here, I have the Koogeek one that uses the tuya protocol ( https://www.amazon.it/gp/product/B07QNT8X61/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1 ) and I have 1.1.1 in both MCU and Wifi modules. Failed to discover in time but will keep looking

**Comment by DrDoom666** [comment] 2019-07-01 15:15
Same here

**Comment by KrtNthny** [comment] 2019-07-17 05:02
Same, My Air-conditioner worked worked well 6 months ago when he first got it going for me now I'm getting this error.  He must be taking a break from the project for a while. I hope he comes back soon.  He did a superb job setting the air conditioner up for me.  It still works, this error just fills the log - 

> [7/12/2019, 3:51:27 PM] Homebridge is running on port 51888.
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> (node:69) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 timeout listeners added. Use emitter.setMaxListeners() to increase limit
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
>

**Comment by TharuMCD** [comment] 2019-07-22 18:22
> My MCU and WIFI Modules are both at 1.0.1. When I do a firmware check my SmartLife app tells me I am on the latest version. I use the following plugs https://www.amazon.ca/TECKIN-Wireless-Compatible-Function-Required/dp/B07PZ7VVGC/ref=sr_1_2_sspa?keywords=smart+plug&qid=1560525067&s=gateway&sr=8-2-spons&psc=1
> So perhaps this is an issue with the newer version of the firmware. Ideally what we need is the ability to specify the devices via IP vs having the homebrige plugin trying to automatically discover them.

Dear iaansari  - very interestingly I think I have the same adapter as you from Amazon but called Woox.  Picture is identical.  Mine are running the same MCU and WiFi Modules 1.0.1 - which the app tells me is the latest version.  However, I still get the failed to discover error message.  Wondered if anyone else had had any success?

Kind regards - Michael

**Comment by PierreBrisorgueil** [comment] 2019-08-23 12:43
+1, MCU & WIFI 1.0.2

probably duplicate of https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/33

**Comment by AMoo-Miki** [comment] 2019-09-06 11:10
I finally got my hands on one of these.

Please give the latest `rc` release a shot by doing `npm i -g homebridge-tuya-lan@rc`. It includes logic to understand this newer API.

A known issue is that the current state is not reported by some devices; they however work fine as soon as you interact with them. I have reached out to Tuya for a solution. 

The [Setup Instructions](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions) have changed in case you need to obtain a fresh `id` and `key`.

**Comment by fraho67** [comment] 2019-09-14 05:46
@AMoo-Miki 

I've purchased three of these https://www.amazon.de/gp/product/B07PS5LRPQ/ref=ppx_yo_dt_b_asin_title_o07_s00?ie=UTF8&psc=1. I'm also getting the "Failed to discover" message, also with the rc-version of TuyaLAN. I've added the ip-addresses in the device block and can see a constant connecting/disconnecting and ERR_PING_TIMED_OUT. I hope you can fix this in some of your next releases and will of course help where I can.

**Comment by AMoo-Miki** [comment] 2019-09-14 08:48
@fraho67, do you know which version of the `rc` you have? You can find that out with `tuya-lan-find -v`.
If you were able to extract the `id` and `key` successfully, the plugin doesn't have a problem understanding the device but something else is blocking the device from responding. If any Tuya app is running on your phone, the devices don't respond to the plugin's discovery attempts. 

If that is not the case with yours, could you please create a new issue and we can dig deep into it there together (thanks for the offer to help debug).

**Comment by deveaf** [comment] 2019-12-08 15:51
AMoo-Miki, with the command tuya-lan-find outputs the following:

Error: EADDRINUSE { Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at /usr/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/lib/proxy.js:95:23
    at /usr/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/lib/ca.js:132:12
    at /usr/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:3888:9
    at /usr/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:473:16
    at replenish (/usr/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:1006:25)
    at iterateeCallback (/usr/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:995:17)
    at /usr/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:969:16
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 8080 }

Сould help in solving the problem?

**Comment by AMoo-Miki** [comment] 2020-02-04 02:10
Closed for inactivity. Please reopen if you continue to need help.

**Closed by AMoo-Miki** 2020-02-04 02:10 UTC

**Comment by ttan** [comment] 2021-01-29 13:35
I'm fighting with new LIDL smart devices, which are just a rebranded Tuya manufactured by Silvercrest.
I have all the devices listed in the Tuya Cloud, got the keys etc and configured in HB, however I keep getting the same error messages:
```
[1/29/2021, 14:32:08] [TuyaLan] Failed to discover Socket 1 (xxxxx) in time but will keep looking.
[1/29/2021, 14:32:08] [TuyaLan] Failed to discover Living room light (yyyyy) in time but will keep looking.
```

Weirdly enough, if I don't set up these accessories, the plugins discover them:

`[1/29/2021, 14:31:12] [TuyaLan] Discovered a device that has not been configured yet (zzzzzz@192.168.1.18)`

**Comment by Alexchev81** [comment] 2021-05-06 15:14
hello I just try @AMoo-Miki solution but now here is the problem 

TuyaDiscovery] Discovery started on port 6666.
[TuyaDiscovery] Discovery started on port 6667.
Starting to advertise 'Homebridge 2848 B2E7' using bonjour-hap backend!
[5/6/2021, 4:18:28 PM] Homebridge v1.3.4 (Homebridge 2848) is running on port 51032.
[5/6/2021, 4:18:29 PM] [TuyaLan] Discovered lumière coté tv bas (bf05403d0f79d7b189f05x) identified as TWLight (3.3)
[TuyaAccessory] Changing ping gap for lumière coté tv bas to 9s
[5/6/2021, 4:18:29 PM] [Google Smart Home] Connected (1) - wss://homebridge-gsh.iot.oz.nu
[5/6/2021, 4:18:29 PM] [TuyaLan] Discovered lumière canapé bas (bfc9cd4483310bfbc6q47z) identified as RGBTWLight (3.3)
[TuyaAccessory] Changing ping gap for lumière canapé bas to 9s
[5/6/2021, 4:18:29 PM] [TuyaLan] Connected to lumière coté tv bas
[TuyaAccessory] Sending first query to lumière coté tv bas (3.3)
[TuyaAccessory] Heard back from lumière coté tv bas with command 10
[5/6/2021, 4:18:29 PM] [TuyaLan] Ready to handle lumière coté tv bas (TWLight:3.3) with signature {"20":false,"21":"white","22":1000,"23":0,"25":"000e0d0000000000000000c80000","26":0}
[5/6/2021, 4:18:29 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:29 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:29 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:29 PM] [TuyaLan] Connected to lumière canapé bas
[TuyaAccessory] Sending first query to lumière canapé bas (3.3)
[5/6/2021, 4:18:29 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:29 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:29 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[TuyaAccessory] Heard back from lumière canapé bas with command 10
[5/6/2021, 4:18:29 PM] [TuyaLan] Ready to handle lumière canapé bas (RGBTWLight:3.3) with signature {"1":false,"2":"white","3":255,"4":255,"5":"ff00000000ffff","101":true}
[TuyaAccessory] Color format for lumière canapé bas (3.3) identified as HEXHSB (length: 14).
[5/6/2021, 4:18:30 PM] [TuyaLan] Discovered lumière TV haut (bff793578be8c70455ftcl) identified as RGBTWLight (3.3)
[TuyaAccessory] Changing ping gap for lumière TV haut to 9s
[5/6/2021, 4:18:30 PM] [TuyaLan] Connected to lumière TV haut
[TuyaAccessory] Sending first query to lumière TV haut (3.3)
[TuyaAccessory] Heard back from lumière TV haut with command 10
[5/6/2021, 4:18:30 PM] [TuyaLan] Ready to handle lumière TV haut (RGBTWLight:3.3) with signature {"20":false,"21":"white","22":1000,"23":0,"24":"000003e803e8","25":"000e0d0000000000000000c80000","26":0,"101":true}
[TuyaAccessory] Color format for lumière TV haut (3.3) is undetectable.
[5/6/2021, 4:18:30 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:31 PM] [TuyaLan] Discovered lumière Alex (bf9b2c149e42fb0101isnf) identified as TWLight (3.3)
[TuyaAccessory] Changing ping gap for lumière Alex to 9s
[5/6/2021, 4:18:31 PM] [TuyaLan] Connected to lumière Alex
[TuyaAccessory] Sending first query to lumière Alex (3.3)
[TuyaAccessory] Heard back from lumière Alex with command 10
[5/6/2021, 4:18:31 PM] [TuyaLan] Ready to handle lumière Alex (TWLight:3.3) with signature {"20":false,"21":"white","22":126,"23":1000,"25":"000e0d0000000000000000c80000","26":0,"41":true}
[5/6/2021, 4:18:31 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:31 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:31 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:32 PM] [TuyaLan] Discovered lumière ma chérie (bf12cbe5962ba879a8itap) identified as TWLight (3.3)
[TuyaAccessory] Changing ping gap for lumière ma chérie to 9s
[5/6/2021, 4:18:32 PM] [TuyaLan] Connected to lumière ma chérie
[TuyaAccessory] Sending first query to lumière ma chérie (3.3)
[TuyaAccessory] Heard back from lumière ma chérie with command 10
[5/6/2021, 4:18:32 PM] [TuyaLan] Ready to handle lumière ma chérie (TWLight:3.3) with signature {"20":false,"21":"white","22":152,"23":560,"25":"000e0d0000000000000000c80000","26":0,"41":true}
[5/6/2021, 4:18:32 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:32 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:32 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:32 PM] [TuyaLan] Discovered lumière salle à manger (bfb8004980a73000d7i8pc) identified as TWLight (3.3)
[TuyaAccessory] Changing ping gap for lumière salle à manger to 9s
[5/6/2021, 4:18:33 PM] [TuyaLan] Connected to lumière salle à manger
[TuyaAccessory] Sending first query to lumière salle à manger (3.3)
[TuyaAccessory] Heard back from lumière salle à manger with command 10
[5/6/2021, 4:18:33 PM] [TuyaLan] Ready to handle lumière salle à manger (TWLight:3.3) with signature {"20":false,"21":"white","22":1000,"23":0,"25":"000e0d0000000000000000c80000","26":0}
[5/6/2021, 4:18:33 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:33 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:33 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:33 PM] [TuyaLan] Discovered lumière tv bas samsung (bf18bffe659100827cnrw8) identified as RGBTWLight (3.3)
[TuyaAccessory] Changing ping gap for lumière tv bas samsung to 9s
[5/6/2021, 4:18:33 PM] [TuyaLan] Connected to lumière tv bas samsung
[TuyaAccessory] Sending first query to lumière tv bas samsung (3.3)
[TuyaAccessory] Heard back from lumière tv bas samsung with command 10
[5/6/2021, 4:18:33 PM] [TuyaLan] Ready to handle lumière tv bas samsung (RGBTWLight:3.3) with signature {"20":false,"21":"white","22":1000,"23":0,"24":"000003e803e8","25":"000e0d0000000000000000c80000","26":0,"101":true}
[TuyaAccessory] Color format for lumière tv bas samsung (3.3) is undetectable.
[5/6/2021, 4:18:33 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:18:53 PM] [Google Smart Home] Finished instance discovery
[5/6/2021, 4:19:08 PM] [Google Smart Home] Sending Sync Request
[5/6/2021, 4:19:08 PM] [Google Smart Home] Please connect with the Google Home app: https://git.io/JfuHC
[5/6/2021, 4:33:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:33:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:33:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:33:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:33:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:33:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:33:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:33:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:33:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:33:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:33:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:33:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:33:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:33:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:48:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:48:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:48:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:48:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:48:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:48:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:48:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 4:48:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 4:48:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:48:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:48:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:48:43 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:48:44 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 4:48:44 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 5:03:44 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 5:03:44 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 5:03:44 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 5:03:44 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 5:03:44 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 5:03:44 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 5:03:44 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number -11 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/6/2021, 5:03:44 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/6/2021, 5:03:44 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 5:03:44 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 5:03:44 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 5:03:44 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 5:03:44 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[5/6/2021, 5:03:44 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.

any ideas ?? thanks
